paustian_book_module.hook_subscriber.article_ui_hooks_subscriber:
      class: Paustian\BookModule\HookSubscriber\ArticleUiHookSubscriber
      arguments:
        - "@translator.default"
      tags:
          - { name: zikula.hook_subscriber, areaName: "subscriber.book.ui_hooks.article" }