paustian_book_module.container.link_container:
        class: Paustian\BookModule\Container\LinkContainer
        arguments:
          - "@translator.default"
          - "@router"
          - "@zikula_permissions_module.api.permission"
        tags:
            - { name: zikula.link_container }